/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Configuracao.java
 *
 * Created on 10/06/2011, 23:17:38
 */

package gui;

import arquivos.Config;
import arquivos.Lang;
import java.awt.Toolkit;
import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author Richard
 */
public class Configuracao extends javax.swing.JFrame {

    /** Creates new form Configuracao */
    public Configuracao()
    {
        config = new Config();
        System.out.println(config.getIdioma());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        URL url = this.getClass().getResource("/gui/tool256.png");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(url));
        jLabel1 = new javax.swing.JLabel();
        idiomas = new javax.swing.JComboBox();
        sCalibracao = new javax.swing.JCheckBox();
        nomeArquivo = new javax.swing.JTextField();
        selecArquivo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Lang.message("option"));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText(Lang.message("lang"));

        ArrayList<String> idiomasDisp = Lang.languages();
        for(int count = 0; count < idiomasDisp.size(); count++)
        {
            idiomas.addItem(idiomasDisp.get(count));
        }

        sCalibracao.setText(Lang.message("save_calibration"));
        sCalibracao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sCalibracaoStateChanged(evt);
            }
        });
        sCalibracao.setSelected(config.getSalvCalibracao());

        if(config.getSalvCalibracao() == true)
        nomeArquivo.setText(config.getCalibracao());
        nomeArquivo.setEnabled(false);

        selecArquivo.setText(Lang.message("selec_file"));
        selecArquivo.setEnabled(false);
        selecArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecArquivoActionPerformed(evt);
            }
        });

        cancelar.setText(Lang.message("cancel"));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ok.setText(Lang.message("ok"));
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sCalibracao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selecArquivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sCalibracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecArquivo)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(ok))
                .addContainerGap())
        );

        idiomas.setSelectedIndex(Lang.getLangSelected());
        System.out.println(Lang.getLangSelected());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sCalibracaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sCalibracaoStateChanged
        if(sCalibracao.isSelected())
        {
            nomeArquivo.setEnabled(true);
            selecArquivo.setEnabled(true);
        }
        else
        {
            nomeArquivo.setEnabled(false);
            selecArquivo.setEnabled(false);
        }
    }//GEN-LAST:event_sCalibracaoStateChanged

    private void selecArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecArquivoActionPerformed
        JFileChooser abrir = new JFileChooser();
        abrir.setMultiSelectionEnabled(false);
        abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(abrir.showOpenDialog(null) == JFileChooser.CANCEL_OPTION)
            return;
        File file = abrir.getSelectedFile();
        BufferedReader arquivo= null;
        try
        {
            arquivo =  new BufferedReader(new FileReader(file));
            String verifica = arquivo.readLine();
            boolean arquivoValido = false;
            if(verifica.equals("<calibration>"))
            {
                arquivo.readLine();
                verifica = arquivo.readLine();
                if(verifica.equals("</calibration>"))
                    arquivoValido = true;
            }
            arquivo.close();
            if(!arquivoValido)
            {
                JOptionPane.showMessageDialog(null,Lang.message("invalid_file"),Lang.message("error"),JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                nomeArquivo.setText(file.getAbsolutePath());
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,Lang.message("err_file_open"),Lang.message("error"),JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selecArquivoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String idioma[] = idiomas.getSelectedItem().toString().split(" - ");
        idioma[0] = idioma[0].replace('-', '_');
        if(!config.getIdioma().equals(idioma[0]))
            JOptionPane.showMessageDialog(null,Lang.message("restart_app"),"",JOptionPane.WARNING_MESSAGE);
        config.setIdioma(idioma[0]);
        if(sCalibracao.isSelected())
        {
            if(new File(nomeArquivo.getText()).exists())
                config.setCalibracao(nomeArquivo.getText());
            else
                sCalibracao.setSelected(false);
        }
        config.setSalvCalibracao(sCalibracao.isSelected());
        config.salvarConfig();
        this.dispose();
    }//GEN-LAST:event_okActionPerformed

    private  Config config;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox idiomas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nomeArquivo;
    private javax.swing.JButton ok;
    private javax.swing.JCheckBox sCalibracao;
    private javax.swing.JButton selecArquivo;
    // End of variables declaration//GEN-END:variables

}
